Repository SIS-Team-24/2023-SIS-Team-24, pull requests merged in 2023-10, with the labels that each got.

#125 Srujan/text font customisation cypress testing
  cypress/e2e/4Questions.cy.js
  cypress/e2e/5TextFontCustomisation.cy.js
Labels: enhancement, testing

#162 Summary Feature Cypress Testing
  client/src/pages/Home.tsx
  cypress/e2e/7SummaryFeature.cy.js
Labels: testing

#164 Emotion Analysis Cypress Testing
  client/src/pages/Home.tsx
  cypress/e2e/8EmotionAnalysis.cy.js
Labels: testing, emotion analysis

#161 Add Spinner component to show when summary API is loading
  .github/workflows/cypress.yml
  client/src/pages/Home.tsx
  client/src/pages/Spinner.tsx
  server/requirements.txt
Labels: enhancement, summary processing, UI/UX

#166 Custom Summary Length (Frontend)
  client/src/pages/Home.tsx
  cypress/e2e/5TextFontCustomisation.cy.js
  server/src/services/summary_service.py
Labels: summary processing, UI/UX

#165 `Spelling and Grammar Errors` Feature
  client/src/pages/Home.tsx
  cypress/e2e/8EmotionAnalysis.cy.js
Labels: enhancement, UI/UX

#168 WIP Fixing `NavBar` Bugs 🐛
  client/src/App.tsx
  client/src/pages/LearnMore.tsx
  client/src/pages/NavigationBar.tsx
  client/src/pages/Questions.tsx
  cypress/e2e/1Home.cy.js
  cypress/e2e/1LearningMaterialSummary.cy.js
  cypress/e2e/2NavigationBar.cy.js
  cypress/e2e/2SummaryHistoryPage.cy.js
  cypress/e2e/3AboutPage.cy.js
  cypress/e2e/3LearnMorePage.js
  cypress/e2e/4AboutPage.cy.js
  cypress/e2e/4Questions.cy.js
  cypress/e2e/5SummaryFeature.cy.js
  cypress/e2e/5TextFontCustomisation.cy.js
  cypress/e2e/6SentimentAnalysis.cy.js
  cypress/e2e/7EmotionAnalysis.cy.js
  cypress/e2e/7SummaryFeature.cy.js
Labels: bug, UI/UX

#173 test: fastapi test for emotion analysis w pytest
  .github/workflows/python.yml
  package.json
  server/requirements.txt
  server/src/services/sentiment_service.py
  server/src/services/summary_service.py
  server/test_route.py
Labels: testing

#172 About page style issues
  client/src/pages/About.tsx
Labels: bug, UI/UX

#171 srujan/homepage-fixes
  client/src/pages/Home.tsx
Labels: UI/UX, emotion analysis

#175 Fixing Cypress Test Issue
  cypress/e2e/3LearnMorePage.cy.js
Labels: bug, testing

#178 FastAPI testing summary
  server/test/__init__.py
  server/test/summary_inputs/__init__.py
  server/test/summary_inputs/long_len.py
  server/test/summary_inputs/medium_len.py
  server/test/summary_inputs/short_len.py
  server/test_route.py
Labels: summary processing, testing

#179 Fast API testing sentiment analysis
  server/test_route.py
Labels: sentiment analysis, testing

#183 Added Email function research as markdown file
  EmailFunctionResearch.md
Labels: documentation, enhancement, store summary output

#180 Srujan/us05 UI fixes
  client/public/favicon.ico
  client/public/index.html
  client/src/pages/Home.tsx
Labels: enhancement, UI/UX

#177 Feature: Key Themes/Concepts (Educational Insights)
  client/src/pages/Home.tsx
  client/src/styles/index.css
  server/src/model/data_model.py
  server/src/routes/summary_routes.py
  server/src/services/summary_service.py
Labels: enhancement

#186 Add pdf input feature
  client/package-lock.json
  client/package.json
  client/src/pages/Home.tsx
Labels: enhancement, UI/UX

#189 Fix performance issues
  .github/workflows/cypress.yml
  .github/workflows/python.yml
  package.json
  server/src/services/summary_service.py
Labels: summary processing

#191 Added Emojis and colour code to Emotion analysis result.
  client/src/pages/Home.tsx
  server/src/services/summary_service.py
Labels: enhancement, emotion analysis

#196 Fix sentiment API issue when token len > 512
  server/src/services/sentiment_service.py
Labels: bug, sentiment analysis, summary processing

#197 Feature: Copy summarised text to clipboard
  client/src/pages/Home.tsx
Labels: enhancement, UI/UX

#194 FastAPI Testing: Key Themes/Concepts (Educational) Insights
  server/test_route.py
Labels: enhancement, testing

#190 Add Share URL feature
  client/public/share-icon.png
  client/src/components/ShareButton.tsx
  client/src/components/Spinner.tsx
  client/src/pages/Home.tsx
  client/src/statePreservationUtils.ts
Labels: enhancement, UI/UX, other functionalities

#198 srujan/cypress_summarise_pdf
  case-study.pdf
  client/src/pages/Home.tsx
  cypress.config.js
  cypress/e2e/8SummarisePDF.cy.js
  cypress/scripts/readPdf.js
  package-lock.json
  package.json
Labels: summary processing, testing

#200 Emailing a Summary Functionality complete
  client/package.json
  client/src/components/EmailFunction.tsx
  client/src/components/HistoryModal.tsx
  client/src/pages/Home.tsx
  package-lock.json
  package.json
  server/src/main.py
  server/src/routes/email_routes.py
Labels: enhancement, summary processing, UI/UX

#199 feat: summarise website using url
  client/src/components/ScrapingInput.tsx
  client/src/pages/Home.tsx
  server/requirements.txt
  server/src/main.py
  server/src/routes/scraper_router.py
Labels: enhancement, other functionalities

#202 Cypress testing for Key Insights, other optimizations
  client/src/pages/Home.tsx
  cypress/e2e/5SummaryFeature.cy.js
  cypress/e2e/6SentimentAnalysis.cy.js
  cypress/e2e/7EmotionAnalysis.cy.js
  cypress/e2e/8SummarisePDF.cy.js
  cypress/e2e/9KeyInsights.cy.js
  cypress/testfiles/case-study.pdf
Labels: testing

#205 UI update - removing placeholder box + rearrange Share and Copy btn
  client/src/pages/Home.tsx
  client/src/styles/sentimentStyles.tsx
Labels: UI/UX

#207 Cypress testing for Summarise Website (URL) feature
  client/src/components/ScrapingInput.tsx
  cypress/e2e/11SummarisingURL.cy.js
Labels: enhancement, testing

#204 added cypress test for share URL feature
  client/src/components/ShareButton.tsx
  client/src/pages/Home.tsx
  cypress/e2e/10SharingSummary.cy.js
Labels: summary processing, testing

#208 fastapi testing website summary
  server/test_route.py
Labels: testing

#203 Home (Bug) Fixes
  client/src/pages/Home.tsx
  client/src/styles/sentimentStyles.tsx
  cypress/e2e/1Home.cy.js
Labels: bug, UI/UX

#210 test: copy to clipboard function
  cypress/e2e/12CopyToClipboard.cy.js
Labels: testing

#209 Click logo to clear all input
  client/src/components/NavigationBar.tsx
  client/src/pages/About.tsx
  client/src/pages/History.tsx
  client/src/pages/Home.tsx
  client/src/pages/LearnMore.tsx
Labels: bug

#211 Email Cypress Finished
  client/src/components/HistoryModal.tsx
  client/src/components/NavigationBar.tsx
  client/src/pages/History.tsx
  cypress/e2e/13EmailFeature.cy.js
Labels: UI/UX, other functionalities, testing
