Repository SIS-Team-24/2023-SIS-Team-24, pull requests merged in 2023-09, with the labels that each got.

#79 [SIS-114] store and display summary history
  client/src/components/HistoryModal.tsx
  client/src/pages/History.tsx
  client/src/pages/Home.tsx
Labels: enhancement

#113 Adjust "Clear History" button position in HistoryPage, and add EmotionLabel to Home Page
  client/src/pages/History.tsx
  client/src/pages/Home.tsx
Labels: enhancement, UI/UX

#78 Add step in webhook trigger to update any deps
  server/src/main.py
Labels: enhancement, other functionalities

#75 Customising Font Display on `Home` Page
  client/src/pages/Home.tsx
  client/src/styles/index.css
Labels: enhancement, UI/UX

#114 FAQ page cypress testing
  .gitignore
  client/src/pages/Questions.tsx
  cypress/e2e/3Questions.cy.js
Labels: enhancement, testing

#116 About page implementation and Cypress Testing (Styling to come later)
  client/src/pages/About.tsx
  cypress/e2e/3AboutPage.cy.js
Labels: UI/UX, testing

#119 update navbar styling and font
  client/src/pages/Home.tsx
  client/src/pages/NavigationBar.tsx
Labels: enhancement, UI/UX

#118 Refine the UI API call function, and text wrap in the text box.
  client/src/pages/Home.tsx
Labels: sentiment analysis, UI/UX, emotion analysis

#122 Fixing the Customise Text Font Feature
  client/src/pages/Home.tsx
Labels: bug, UI/UX

#121 [Text Insight Issue #120] US-19: Handle long user input
  server/requirements.txt
  server/src/services/common.py
  server/src/services/sentiment_service.py
  server/src/services/summary_service.py
Labels: enhancement, summary processing

#133 Srujan/UI UX fixes
  client/src/pages/About.tsx
  client/src/pages/History.tsx
  client/src/pages/Home.tsx
  client/src/pages/LearningMaterialSummary.tsx
  client/src/pages/NavigationBar.tsx
  client/src/pages/Questions.tsx
Labels: enhancement, summary processing, UI/UX

#132 US-17: Custom word length (Backend only)
  server/src/model/data_model.py
  server/src/model/db_model.py
  server/src/routes/summary_routes.py
  server/src/services/summary_service.py
Labels: enhancement, summary processing

#135 test: cypress tests for sentiment analysis
  client/src/pages/Home.tsx
  cypress/e2e/6SentimentAnalysis.cy.js
Labels: sentiment analysis, testing

#131 Fixed the page margin inconsistency, History page button style, and output text box issues.
  client/src/pages/History.tsx
  client/src/pages/Home.tsx
  client/src/pages/Questions.tsx
Labels: bug, UI/UX

#160 Add default summary length options, use separate data class for API input
  client/src/pages/Home.tsx
  server/src/model/data_model.py
  server/src/routes/summary_routes.py
  server/src/services/summary_service.py
Labels: bug, summary processing
